Repository atom-community/atom-ide-base, pull requests merged in 2021-01, with the labels that each got.

#44 chore: bump devDedendencies
  .npmrc
  package.json
  pnpm-lock.yaml
Labels: Dependencies

#43 docs: use docblocks for types
  types-packages/busy-signal.d.ts
  types-packages/datatip.d.ts
  types-packages/definitions.d.ts
  types-packages/find-references.d.ts
  types-packages/hyperclick.d.ts
  types-packages/main.d.ts
  types-packages/markdown-service.d.ts
  types-packages/outline.d.ts
Labels: documentation

#45 fix: make addModifierProvider and createPinnedDataTip optional
  types-packages/datatip.d.ts
Labels: bug

#46 docs: update busy-signal.d.ts
  types-packages/busy-signal.d.ts
Labels: documentation

#47 fix: bump package-deps
  .github/workflows/CI.yml
  .gitignore
  package.json
  pnpm-lock.yaml
  script/install-package-deps.js
  spec/runner.js
  src-package/main.ts
Labels: Dependencies
